/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth-layout`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/recover`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/mesas` | `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/usuarios` | `/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/reservas` | `/reservas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/configuracion` | `/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/autenticacion`; params?: Router.UnknownInputParams; } | { pathname: `/autenticacion/iniciar-sesion`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth-layout`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/recover`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(principal)'}/index` | `/index`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(principal)'}/mesas` | `/mesas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(principal)'}/usuarios` | `/usuarios`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(principal)'}/reservas` | `/reservas`; params?: Router.UnknownOutputParams; } | { pathname: `${'/(principal)'}/configuracion` | `/configuracion`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; } | { pathname: `/autenticacion`; params?: Router.UnknownOutputParams; } | { pathname: `/autenticacion/iniciar-sesion`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth-layout${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/recover${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `${'/(principal)'}/index${`?${string}` | `#${string}` | ''}` | `/index${`?${string}` | `#${string}` | ''}` | `${'/(principal)'}/mesas${`?${string}` | `#${string}` | ''}` | `/mesas${`?${string}` | `#${string}` | ''}` | `${'/(principal)'}/usuarios${`?${string}` | `#${string}` | ''}` | `/usuarios${`?${string}` | `#${string}` | ''}` | `${'/(principal)'}/reservas${`?${string}` | `#${string}` | ''}` | `/reservas${`?${string}` | `#${string}` | ''}` | `${'/(principal)'}/configuracion${`?${string}` | `#${string}` | ''}` | `/configuracion${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | `/autenticacion${`?${string}` | `#${string}` | ''}` | `/autenticacion/iniciar-sesion${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth-layout`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/recover`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/index` | `/index`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/mesas` | `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/usuarios` | `/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/reservas` | `/reservas`; params?: Router.UnknownInputParams; } | { pathname: `${'/(principal)'}/configuracion` | `/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; } | { pathname: `/autenticacion`; params?: Router.UnknownInputParams; } | { pathname: `/autenticacion/iniciar-sesion`; params?: Router.UnknownInputParams; };
    }
  }
}
