/* eslint-disable */
import * as Router from 'expo-router';

export * from 'expo-router';

declare module 'expo-router' {
  export namespace ExpoRouter {
    export interface __routes<T extends string | object = string> {
      hrefInputParams: { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth-layout`; params?: Router.UnknownInputParams; } | { pathname: `/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `/recover`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/reservas`; params?: Router.UnknownInputParams; } | { pathname: `/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colores`; params?: Router.UnknownInputParams; } | { pathname: `/autenticacion/index`; params?: Router.UnknownInputParams; } | { pathname: `/autenticacion/iniciar-sesion`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
      hrefOutputParams: { pathname: Router.RelativePathString, params?: Router.UnknownOutputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownOutputParams } | { pathname: `/auth-layout`; params?: Router.UnknownOutputParams; } | { pathname: `/configuracion`; params?: Router.UnknownOutputParams; } | { pathname: `/`; params?: Router.UnknownOutputParams; } | { pathname: `/login`; params?: Router.UnknownOutputParams; } | { pathname: `/mesas`; params?: Router.UnknownOutputParams; } | { pathname: `/recover`; params?: Router.UnknownOutputParams; } | { pathname: `/register`; params?: Router.UnknownOutputParams; } | { pathname: `/reservas`; params?: Router.UnknownOutputParams; } | { pathname: `/usuarios`; params?: Router.UnknownOutputParams; } | { pathname: `/../constants/Colores`; params?: Router.UnknownOutputParams; } | { pathname: `/autenticacion/index`; params?: Router.UnknownOutputParams; } | { pathname: `/autenticacion/iniciar-sesion`; params?: Router.UnknownOutputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownOutputParams; };
      href: Router.RelativePathString | Router.ExternalPathString | `/auth-layout${`?${string}` | `#${string}` | ''}` | `/configuracion${`?${string}` | `#${string}` | ''}` | `/${`?${string}` | `#${string}` | ''}` | `/login${`?${string}` | `#${string}` | ''}` | `/mesas${`?${string}` | `#${string}` | ''}` | `/recover${`?${string}` | `#${string}` | ''}` | `/register${`?${string}` | `#${string}` | ''}` | `/reservas${`?${string}` | `#${string}` | ''}` | `/usuarios${`?${string}` | `#${string}` | ''}` | `/../constants/Colores${`?${string}` | `#${string}` | ''}` | `/autenticacion/index${`?${string}` | `#${string}` | ''}` | `/autenticacion/iniciar-sesion${`?${string}` | `#${string}` | ''}` | `/_sitemap${`?${string}` | `#${string}` | ''}` | { pathname: Router.RelativePathString, params?: Router.UnknownInputParams } | { pathname: Router.ExternalPathString, params?: Router.UnknownInputParams } | { pathname: `/auth-layout`; params?: Router.UnknownInputParams; } | { pathname: `/configuracion`; params?: Router.UnknownInputParams; } | { pathname: `/`; params?: Router.UnknownInputParams; } | { pathname: `/login`; params?: Router.UnknownInputParams; } | { pathname: `/mesas`; params?: Router.UnknownInputParams; } | { pathname: `/recover`; params?: Router.UnknownInputParams; } | { pathname: `/register`; params?: Router.UnknownInputParams; } | { pathname: `/reservas`; params?: Router.UnknownInputParams; } | { pathname: `/usuarios`; params?: Router.UnknownInputParams; } | { pathname: `/../constants/Colores`; params?: Router.UnknownInputParams; } | { pathname: `/autenticacion/index`; params?: Router.UnknownInputParams; } | { pathname: `/autenticacion/iniciar-sesion`; params?: Router.UnknownInputParams; } | { pathname: `/_sitemap`; params?: Router.UnknownInputParams; };
    }
  }
}
